name: Build and Push to Azure Container Registry


on:
  push:
    branches:
      - cicd/azure_webapp_deploy_workflow

permissions:
  id-token: write
  contents: read

env:
  ACR_REGISTRY: ${{vars.ACR_REGISTRY}} # Replace with acr login server
  AZURE_WEBAPP_NAME: ${{vars.AZURE_WEBAPP_NAME}}
  IMAGE_NAME: ${{vars.IMAGE_NAME}} # Replace  with app/image name
  IMAGE_TAG: ${{github.sha}} # Use commit SHA as tag
jobs:
  # ==========================================
  # Lint & Test (Optional but Recommended)
  # ==========================================
  lint_and_test:
      name: Lint and Test
      runs-on: ubuntu-latest
      steps:
          # check out the repository code
          - name: Checkout Code
            uses: actions/checkout@v4

          #   Setup Node.js environment
          - name: Setup Node.js
            uses: actions/setup-node@v4
            with:
              node-version: '21'
              cache: 'npm'   # or 'npm' or 'yarn'

              # Install dependencies
          - name: Install dependencies
            run: npm ci

            # lint checking
          - name: Run linters
            run: npm run lint


  # ==========================================
  # Build & Push Docker Image to ACR
  # ==========================================
  build_and_push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: [lint_and_test]   # make sure lint and text pass

    steps:
      # check out the repository code
      - name: Checkout Code
        uses: actions/checkout@v4
      #     # Login to Azure
      # - name: Azure login
      #   uses: azure/login@v2
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}
      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to Azure Container Registry
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{env.ACR_REGISTRY}}
          username: ${{secrets.ACR_USERNAME}} # GitHub Secret: Service Principal ID or ACR Admin User
          password: ${{secrets.ACR_PASSWORD}} # GitHub Secret: Service Principal Password or ACR Admin Password

      # Build and push Docker image to ACR
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{env.ACR_REGISTRY}}/${{env.IMAGE_NAME}}:${{github.sha}}
            ${{env.ACR_REGISTRY}}/${{env.IMAGE_NAME}}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
    # Login to Azure
      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        
          # Deploy app to Azure
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          images: ${{env.ACR_REGISTRY}}/${{env.IMAGE_NAME}}:latest